package com.magic.acme.assist.jpa.xtt.entity;
// Generated 2017-6-22 10:27:00 by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HandshakeCargoDiscrepancy generated by hbm2java
 */
@Entity
@Table(name = "handshake_cargo_discrepancy", schema = "public")
public class HandshakeCargoDiscrepancy implements java.io.Serializable {

    private long id;
    private String handshakeId;
    private String comment;
    private Integer orderLineIndex;
    private Integer tuDamage;
    private Integer tuLoss;
    private String cargoName;
    private String cargoCode;
    private String unit;
    private BigDecimal unitPrice;

    private Handshake handshake;

    public HandshakeCargoDiscrepancy() {
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "handshake_id", insertable = false, updatable = false)
    public String getHandshakeId() {
        return this.handshakeId;
    }

    public void setHandshakeId(String handshakeId) {
        this.handshakeId = handshakeId;
    }

    @Column(name = "comment")
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Column(name = "order_line_index")
    public Integer getOrderLineIndex() {
        return this.orderLineIndex;
    }

    public void setOrderLineIndex(Integer orderLineIndex) {
        this.orderLineIndex = orderLineIndex;
    }

    @Column(name = "tu_damage")
    public Integer getTuDamage() {
        return this.tuDamage;
    }

    public void setTuDamage(Integer tuDamage) {
        this.tuDamage = tuDamage;
    }

    @Column(name = "tu_loss")
    public Integer getTuLoss() {
        return this.tuLoss;
    }

    public void setTuLoss(Integer tuLoss) {
        this.tuLoss = tuLoss;
    }

    @Column(name = "cargo_name")
    public String getCargoName() {
        return this.cargoName;
    }

    public void setCargoName(String cargoName) {
        this.cargoName = cargoName;
    }

    @Column(name = "cargo_code", length = 1255)
    public String getCargoCode() {
        return this.cargoCode;
    }

    public void setCargoCode(String cargoCode) {
        this.cargoCode = cargoCode;
    }

    @Column(name = "unit")
    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    @Column(name = "unit_price")
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "handshake_id", nullable = false)
    public Handshake getHandshake() {
        return handshake;
    }

    public void setHandshake(Handshake handshake) {
        this.handshake = handshake;
    }
}
