package com.magic.acme.assist.jpa.xtt.entity;
// Generated 2017-6-22 10:27:00 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HandshakeOrderLineRejection generated by hbm2java
 */
@Entity
@Table(name = "handshake_order_line_rejection", schema = "public")
public class HandshakeOrderLineRejection implements java.io.Serializable {

    private long id;
    private String handshakeId;
    private int rejectedQuantity;
    private Integer reasonId;
    private int orderLineIndex;
    private String comment;
    private String cargoCode;
    private String cargoName;
    private String unit;

    private Handshake handshake;

    public HandshakeOrderLineRejection() {
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "handshake_id", insertable = false, updatable = false)
    public String getHandshakeId() {
        return this.handshakeId;
    }

    public void setHandshakeId(String handshakeId) {
        this.handshakeId = handshakeId;
    }

    @Column(name = "rejected_quantity", nullable = false)
    public int getRejectedQuantity() {
        return this.rejectedQuantity;
    }

    public void setRejectedQuantity(int rejectedQuantity) {
        this.rejectedQuantity = rejectedQuantity;
    }

    @Column(name = "reason_id")
    public Integer getReasonId() {
        return this.reasonId;
    }

    public void setReasonId(Integer reasonId) {
        this.reasonId = reasonId;
    }

    @Column(name = "order_line_index", nullable = false)
    public int getOrderLineIndex() {
        return this.orderLineIndex;
    }

    public void setOrderLineIndex(int orderLineIndex) {
        this.orderLineIndex = orderLineIndex;
    }

    @Column(name = "comment")
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Column(name = "cargo_code")
    public String getCargoCode() {
        return this.cargoCode;
    }

    public void setCargoCode(String cargoCode) {
        this.cargoCode = cargoCode;
    }

    @Column(name = "cargo_name")
    public String getCargoName() {
        return this.cargoName;
    }

    public void setCargoName(String cargoName) {
        this.cargoName = cargoName;
    }

    @Column(name = "unit")
    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "handshake_id", nullable = false)
    public Handshake getHandshake() {
        return handshake;
    }

    public void setHandshake(Handshake handshake) {
        this.handshake = handshake;
    }
}
