package com.magic.acme.assist.jpa.xtt.entity;
// Generated 2017-6-22 10:27:00 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HandshakeNoCargo generated by hbm2java
 */
@Entity
@Table(name = "handshake_no_cargo", schema = "public")
public class HandshakeNoCargo implements java.io.Serializable {

    private long id;
    private String handshakeId;
    private String comment;
    private Integer orderLineIndex;
    private Integer pickedQuantity;

    private Handshake handshake;

    public HandshakeNoCargo() {
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "handshake_id", insertable = false, updatable = false)
    public String getHandshakeId() {
        return this.handshakeId;
    }

    public void setHandshakeId(String handshakeId) {
        this.handshakeId = handshakeId;
    }

    @Column(name = "comment", nullable = false)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Column(name = "order_line_index")
    public Integer getOrderLineIndex() {
        return this.orderLineIndex;
    }

    public void setOrderLineIndex(Integer orderLineIndex) {
        this.orderLineIndex = orderLineIndex;
    }

    @Column(name = "picked_quantity")
    public Integer getPickedQuantity() {
        return this.pickedQuantity;
    }

    public void setPickedQuantity(Integer pickedQuantity) {
        this.pickedQuantity = pickedQuantity;
    }

    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "handshake_id", nullable = false)
    public Handshake getHandshake() {
        return handshake;
    }

    public void setHandshake(Handshake handshake) {
        this.handshake = handshake;
    }
}
