package com.magic.acme.assist.jpa.xtt.entity;
// Generated 2017-6-22 10:27:00 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HandshakeOrder generated by hbm2java
 */
@Entity
@Table(name = "handshake_order", schema = "public")
public class HandshakeOrder implements java.io.Serializable {

    private long id;
    private String handshakeId;
    private String barcodeNumber;
    private String tokenId;
    private String phoneNumber;
    private int ownerRole;
    private Integer errorCode;
    private String errorMessage;
    private Integer handshakeMode;

    private Handshake handshake;

    public HandshakeOrder() {
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "handshake_id", insertable = false, updatable = false)
    public String getHandshakeId() {
        return this.handshakeId;
    }

    public void setHandshakeId(String handshakeId) {
        this.handshakeId = handshakeId;
    }

    @Column(name = "barcode_number", length = 13)
    public String getBarcodeNumber() {
        return this.barcodeNumber;
    }

    public void setBarcodeNumber(String barcodeNumber) {
        this.barcodeNumber = barcodeNumber;
    }

    @Column(name = "token_id", nullable = false)
    public String getTokenId() {
        return this.tokenId;
    }

    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }

    @Column(name = "phone_number")
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Column(name = "owner_role", nullable = false)
    public int getOwnerRole() {
        return this.ownerRole;
    }

    public void setOwnerRole(int ownerRole) {
        this.ownerRole = ownerRole;
    }

    @Column(name = "error_code")
    public Integer getErrorCode() {
        return this.errorCode;
    }

    public void setErrorCode(Integer errorCode) {
        this.errorCode = errorCode;
    }

    @Column(name = "error_message")
    public String getErrorMessage() {
        return this.errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    @Column(name = "handshake_mode")
    public Integer getHandshakeMode() {
        return this.handshakeMode;
    }

    public void setHandshakeMode(Integer handshakeMode) {
        this.handshakeMode = handshakeMode;
    }

    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "handshake_id", nullable = false)
    public Handshake getHandshake() {
        return handshake;
    }

    public void setHandshake(Handshake handshake) {
        this.handshake = handshake;
    }
}
